[build]
  publish = "Task"  # Replace with the directory containing your index.html
  command = "pip install -r Task/requirements.txt && python Task/Tasks_Google_Play_store_Analysis_NullClass.py"

[context.production.environment]
  PYTHON_VERSION = "3.9"
