[build]
  publish = "Task"  # Replace with the directory containing your index.html
  command = "apt-get update && apt-get install -y clang libcurl4-openssl-dev && pip install -r requirements.txt && python Tasks_Google_Play_store_Analysis_NullClass.py"

[context.production.environment]
  PYTHON_VERSION = "3.13"

[[plugins]]
  package = "@netlify/plugin-lifecycle-env"

[functions]
  node_bundler = "esbuild"
